name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Package
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !/.specstory/

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Upgrade npm
        run: npm i -g npm@latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to NPM
        run: pnpm run publish:ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  changelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !/.specstory/

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Release Page
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !/.specstory/

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Packages
        run: pnpm run build

      - name: Build Document
        run: pnpm run docs:build

      - name: Zip destyler.org
        run: npx tsx scripts/zip.ts document/dist docs-dist

      - name: Deploy destyler.org
        run: npx tsx scripts/deploy.ts ${TOKEN} ${ENV} ${SERVICE} docs-dist.zip
        env:
          TOKEN: ${{secrets.ZEABUR_TOKEN}}
          ENV: ${{secrets.DESTYLER_ENV}}
          SERVICE: ${{secrets.DESTYLER_ORG}}

      - name: Build Storybook
        run: pnpm run storybook:build

      - name: Zip storybook.destyler.org
        run: npx tsx scripts/zip.ts storybook/dist storybook-dist

      - name: Deploy storybook.destyler.org
        run: npx tsx scripts/deploy.ts ${TOKEN} ${ENV} ${SERVICE} storybook-dist.zip
        env:
          TOKEN: ${{secrets.ZEABUR_TOKEN}}
          ENV: ${{secrets.DESTYLER_ENV}}
          SERVICE: ${{secrets.STORYBOOK_ORG}}

